{
    parserClass="com.technophobia.substeps.idea.parser.SubstepsParser"
    parserUtilClass="com.technophobia.substeps.idea.parser.SubstepsParserUtil"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Substeps"
    psiImplClassSuffix="Impl"
    psiPackage="com.technophobia.substeps.idea.psi"
    psiImplPackage="com.technophobia.substeps.idea.psi.impl"

    elementTypeHolderClass="com.technophobia.substeps.idea.lexer.SubstepsTypes"
    elementTypeClass="com.technophobia.substeps.idea.lexer.SubstepsElement"
    tokenTypeClass="com.technophobia.substeps.idea.lexer.SubstepsToken"

    tokens=[
        DEFINE='Define:'
        var_start='<'
        var_end='>'
        text="regexp:[^<>:\n \t][^<>:\n]*"
        eol="regexp:\n"
        comment="regexp:^#.*\n"
    ]
}

substepsFile ::= (definition | comment | eol)*

definition ::= DEFINE step_def eol step_impls {pin=1}

step_impls ::= (step_def eol)*

step_def ::= ( var_part | step_part )*

var_part ::= var_start text var_end {pin=3}

step_part ::= text