{
    parserClass="com.technophobia.substeps.idea.parser.SubstepsParser"
    parserUtilClass="com.technophobia.substeps.idea.parser.SubstepsParserUtil"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Substeps"
    psiImplClassSuffix="Impl"
    psiPackage="com.technophobia.substeps.idea.psi"
    psiImplPackage="com.technophobia.substeps.idea.psi.impl"

    elementTypeHolderClass="com.technophobia.substeps.idea.lexer.SubstepsTypes"
    elementTypeClass="com.technophobia.substeps.idea.lexer.SubstepsElement"
    tokenTypeClass="com.technophobia.substeps.idea.lexer.SubstepsToken"

    tokens=[
        DEFINE='Define:'
        step_part="regexp:[^<>:\n]*"
        var_name="regexp:[^<>:\n]*"
        sp="regexp:[ \t\f]"
    ]
}

substepsFile ::= definition*

definition ::= DEFINE sp* step_def step_impls

step_def ::= ( var_def | defn_part )+ '\n'

private step_impls ::= (step_impl '\n')*

defn_part ::= step_part

var_def ::= "<" var_name ">"

step_impl ::= ( impl_part | var_usage )+

impl_part ::= step_part

var_usage ::= '<' var_name '>'
